### ISSUE TITLE
Question about the generator output.

### ISSUE THREAD

**Issue by YongjianDeng** [alexzzhu/EventGAN#2]
Hi,

I'm wondering if your generated fake event in the form of volume but not point cloud? It is like you are trying to achieve the volume-like event representation but not the raw events[x, y, t, p] form, right?

Best,
Ty

**Comment by alexzzhu** [comment]
Right, the network is predicted an event volume, rather than discrete events as a point cloud.

**Comment by YongjianDeng** [comment]
Hi,

Sorry to spare you so much time. After the experiment for optical flow prediction. I found that the ground truth is far from the prediction results, and the prediction results outperform the ground truth in terms of the images' warping task. Did you encounter this situation or is there something wrong with my setup? Does that mean the ground truth with lower accuracy compared to the prediction results trained using warping loss? If it is, how can we measure the optical flow quality using this dataset?

Ps: Before comparing, I have already transform the predicted flow from the range [-1, 1] to pixel level flow just like the ground truth is.

Best,
Ty

**Comment by alexzzhu** [comment]
No problem! How exactly are you measuring the error wrt to the ground truth? And how different are the losses? Please note that the ground truth timestamps do not align with the image timestamps, and so some interpolation is necessary. Please see this script for an example of how we compute the errors: https://github.com/daniilidis-group/EV-FlowNet/blob/cf801ef5e4b112e08bfe6eac4f0878b1f5aac2fe/src/test.py#L107

**Comment by YongjianDeng** [comment]
Hi,

Thx for your timely response. I did follow this script to measure the error. However, from the visualization result, warping results from the predicted sparse flow better than the warping performance using the gt flow. My question is if in some situations, predicted flow is more accurate than gt flow?

Best,

**Comment by alexzzhu** [comment]
That's definitely possible. The ground truth was measured with egomotion+depth, and so there may be errors due to error in either measurement.

**Comment by YongjianDeng** [comment]
I appreciate your patient response, which helps me a lot.
