### ISSUE TITLE
Frames and Ground truth depth map sync

### ISSUE THREAD

**Issue by SoikatHasanAhmed** [alexzzhu/EventGAN#3]
I am facing issue to sync the frames and ground truth depth map. For example in indoor fly 1 the number of games 2206 and the start time is 4.0  so we have almost 2202 frames, on the other hand depth map has 1399 elements. So, could you tell me what's the way to sync them? Thanks very much!

**Comment by alexzzhu** [comment]
I'm not sure if this is in the right repo, as we don't use the ground truth depths for EventGAN. Do you mean the depth maps for MVSEC? 

If so, the depth maps are synced to the lidar scan times, from which they were generated, to avoid any interpolation. Typically, you would need to interpolate the depth maps on your end to sync with the frames. A simple way would be to take the depth map with timestamp closest to the curent frame.

**Comment by SoikatHasanAhmed** [comment]
I apologize to ask the question about the depth maps in this repo. I could not find any repo for the dataset.
Yes, I am working on MVSEC dataset. I will try to interpolate and let you know the update.

**Comment by alexzzhu** [comment]
No problem. Here is the repo for MVSEC: https://github.com/daniilidis-group/mvsec.

**Comment by SoikatHasanAhmed** [comment]
Thank you @alexzzhu for your instant response everything is working fine.
